# Generated by Django 4.1.2 on 2022-10-09 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_job_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='category',
        ),
    ]
